spring:
  application:
    name: ImoocCustomer
  datasource:  # ∵ pom 中依赖了 mysql-connector-java ∴ 这里要配置数据源信息，否则无法启动应用
    url: jdbc:mysql://localhost:3306/passbook?autoReconnect=true  # url 上的参数：断开连接后会自动重连
    username: root
    password: frank914
  kafka:
    bootstrap-servers: localhost:9092  # Kafka broker server 地址（9092是其默认端口号）
    consumer:
      group-id: passbook  # kafka 消费者组
    listener:
      concurrency: 4  # 一个消费者组里包含4个消费者，可同时消费4个 partition
  data:
    hbase:
      quorum: localhost:2181  # Hbase 内置的 zookeeper server 地址（2181是其默认端口号）
      rootDir: file:///Users/myjiang/Documents/Dev/system-design/imooc-passbook/hbase_data/root_dir  # Hbase 的数据存储目录（一般应设为 HDFS 地址，这里配置为本机地址）
      nodeParent: /hbase  # Hbase 在 zookeeper 上的根节点
  redis:
    host: localhost
    port: 6379  # redis 默认端口号

server:
  port: 9528

logging:
  level:
    root: debug
  file:
    path: /log
    name: imooc-customer.log