spring:
  application:
    name: ImoocMerchants
  datasource:  # ∵ pom 中依赖了 mysql-connector-java ∴ 这里要配置数据源信息，否则无法启动应用
    url: jdbc:mysql://localhost:3306/passbook?autoReconnect=true  # url 上的参数：断开连接后会自动重连
    username: root
    password: frank914
  kafka:
    bootstrap-servers: localhost:9092  # Kafka broker server 地址
    consumer:
      group-id: passbook  # kafka 消费者组
    listener:
      concurrency: 4  # 一个消费者组里包含4个消费者，可同时消费4个 partition

server:
  port: 9527

logging:
  level:
    root: debug
  file:
    name: imooc-merchants.log
